### YamlMime:Role 
title: 개발자 
metadata: 
  title: 개발자 
  description: 개발자는 솔루션을 설계, 구축, 테스트 및 유지합니다. 개발자는 솔루션 아키텍처 및 고객과 협력하여 애플리케이션 및 서비스를 구현합니다.
uid: role.developer 
summary: | 
  개발자는 솔루션을 설계, 구축, 테스트 및 유지합니다. 개발자는 솔루션 아키텍처 및 고객과 협력하여 애플리케이션 및 서비스를 구현합니다. 
subTitle: 개발자는 클라우드 솔루션을 설계, 구축, 테스트 및 유지합니다.
certificationPaths: 
- title: Azure 개발자
  linkedInKeywords: Azure 개발자
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Dynamics 365 금융 및 운영 앱 개발자
  linkedInKeywords: Dynamics 365 금융 및 운영 앱 개발자
  uid: certification.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Microsoft 365 개발자
  linkedInKeywords: Microsoft 365 개발자
  uid: certification.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
- title: Power Apps + Dynamics 365 개발자
  linkedInKeywords: Power Apps + Dynamics 365 개발자
  uid: certification.power-apps-and-d365-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-apps-and-d365-developer-associate
    levels:
    - intermediate 
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-203
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-apps-and-d365-developer-associate
  requiredExams:
  - uid: exam.pl-900
resources:
- title: Microsoft 교육 및 인증 가이드
  description: 간략 교육 및 인증 가이드에서 모든 인증을 설명합니다.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: 교육 및 인증 포스터
  description: 이 교육 및 인증 포스터를 통해 성공을 위한 길을 선택합니다.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: 인증 지원
  href: ../help.md
  description: Microsoft 인증 지원 포럼에서 도움을 받으십시오. 포럼 조정자는 월요일에서 금요일까지 업무일 하루만에 응답할 것입니다.
